export const morningTitles: Record<string, string[]> = {
	eng: [
		"Begin with His Word 📖",
		"Walk in His Light ✨",
		"Trust the Lord Today 🙏",
		"His Grace Is Enough ❤️",
		"Seek Him with All Your Heart",
		"Let His Word Lead You 📖",
		"Hope in the Lord ✨",
		"Choose Faith Today 🙏",
		"God Is Your Strength ❤️",
		"Rejoice in the Lord ✨",
		"Stand Firm in Faith 📖",
		"His Mercies Are New 🙏",
		"Walk by Faith ❤️",
		"Be Strong in the Lord ✨",
		"Delight in His Word 📖",
		"Give Your Day to God 🙏",
		"Keep Your Eyes on Jesus ❤️",
		"His Word Gives Life ✨",
		"Rest in His Promises 📖",
		"Draw Near to God 🙏",
		"Let Faith Guide You ❤️",
		"God Is Your Refuge ✨",
		"Follow His Ways 📖",
		"Trust His Perfect Plan 🙏",
		"Live in His Grace ❤️",
		"Be Still Before God ✨",
		"Let His Light Shine Through You 📖",
		"Rejoice in His Faithfulness 🙏",
		"Receive His Peace ❤️",
		"Walk Humbly with God ✨",
		"Abide in His Word 📖"
	],

	en: [
		"Begin with His Word 📖",
		"Walk in His Light ✨",
		"Trust the Lord Today 🙏",
		"His Grace Is Enough ❤️",
		"Seek Him with All Your Heart",
		"Let His Word Lead You 📖",
		"Hope in the Lord ✨",
		"Choose Faith Today 🙏",
		"God Is Your Strength ❤️",
		"Rejoice in the Lord ✨",
		"Stand Firm in Faith 📖",
		"His Mercies Are New 🙏",
		"Walk by Faith ❤️",
		"Be Strong in the Lord ✨",
		"Delight in His Word 📖",
		"Give Your Day to God 🙏",
		"Keep Your Eyes on Jesus ❤️",
		"His Word Gives Life ✨",
		"Rest in His Promises 📖",
		"Draw Near to God 🙏",
		"Let Faith Guide You ❤️",
		"God Is Your Refuge ✨",
		"Follow His Ways 📖",
		"Trust His Perfect Plan 🙏",
		"Live in His Grace ❤️",
		"Be Still Before God ✨",
		"Let His Light Shine Through You 📖",
		"Rejoice in His Faithfulness 🙏",
		"Receive His Peace ❤️",
		"Walk Humbly with God ✨",
		"Abide in His Word 📖"
	],

	es: [
		"Comienza con Su Palabra 📖",
		"Camina en Su Luz ✨",
		"Confía en el Señor Hoy 🙏",
		"Su Gracia es Suficiente ❤️",
		"Búscalo con Todo tu Corazón",
		"Deja que Su Palabra te Guíe 📖",
		"Espera en el Señor ✨",
		"Elige la Fe Hoy 🙏",
		"Dios es tu Fortaleza ❤️",
		"Alégrate en el Señor ✨",
		"Permanece Firme en la Fe 📖",
		"Sus Misericordias son Nuevas 🙏",
		"Camina por Fe ❤️",
		"Sé Fuerte en el Señor ✨",
		"Deléitate en Su Palabra 📖",
		"Entrega tu Día a Dios 🙏",
		"Mantén tus Ojos en Jesús ❤️",
		"Su Palabra da Vida ✨",
		"Descansa en Sus Promesas 📖",
		"Acércate a Dios 🙏",
		"Deja que la Fe te Guíe ❤️",
		"Dios es tu Refugio ✨",
		"Sigue Sus Caminos 📖",
		"Confía en Su Plan Perfecto 🙏",
		"Vive en Su Gracia ❤️",
		"Quédate en Silencio ante Dios ✨",
		"Deja que Su Luz Brille en Ti 📖",
		"Alégrate en Su Fidelidad 🙏",
		"Recibe Su Paz ❤️",
		"Camina Humildemente con Dios ✨",
		"Permanece en Su Palabra 📖"
	],

	pt: [
		"Comece com a Sua Palavra 📖",
		"Ande na Sua Luz ✨",
		"Confie no Senhor Hoje 🙏",
		"A Sua Graça é Suficiente ❤️",
		"Busque-O de Todo o Coração",
		"Deixe a Sua Palavra Guiar Você 📖",
		"Espere no Senhor ✨",
		"Escolha a Fé Hoje 🙏",
		"Deus é a Sua Força ❤️",
		"Alegre-se no Senhor ✨",
		"Permaneça Firme na Fé 📖",
		"As Suas Misericórdias se Renovam 🙏",
		"Viva pela Fé ❤️",
		"Seja Forte no Senhor ✨",
		"Alegre-se na Sua Palavra 📖",
		"Entregue o Seu Dia a Deus 🙏",
		"Mantenha os Olhos em Jesus ❤️",
		"A Sua Palavra Dá Vida ✨",
		"Descanse nas Suas Promessas 📖",
		"Aproxime-se de Deus 🙏",
		"Deixe a Fé Guiar Você ❤️",
		"Deus é o Seu Refúgio ✨",
		"Siga os Seus Caminhos 📖",
		"Confie no Seu Plano Perfeito 🙏",
		"Viva na Sua Graça ❤️",
		"Aquieta-te diante de Deus ✨",
		"Deixe a Sua Luz Brilhar em Você 📖",
		"Alegre-se na Sua Fidelidade 🙏",
		"Receba a Sua Paz ❤️",
		"Ande Humildemente com Deus ✨",
		"Permaneça na Sua Palavra 📖"
	],

	fr: [
		"Commencez par Sa Parole 📖",
		"Marchez dans Sa Lumière ✨",
		"Faites Confiance au Seigneur Aujourd'hui 🙏",
		"Sa Grâce Vous Suffit ❤️",
		"Cherchez-Le de Tout Votre Cœur",
		"Laissez Sa Parole Vous Guider 📖",
		"Espérez dans le Seigneur ✨",
		"Choisissez la Foi Aujourd'hui 🙏",
		"Dieu est Votre Force ❤️",
		"Réjouissez-vous dans le Seigneur ✨",
		"Demeurez Fermes dans la Foi 📖",
		"Ses Miséricordes se Renouvellent 🙏",
		"Marchez par la Foi ❤️",
		"Fortifiez-vous dans le Seigneur ✨",
		"Faites Vos Délices de Sa Parole 📖",
		"Confiez Votre Journée à Dieu 🙏",
		"Gardez les Yeux Fixés sur Jésus ❤️",
		"Sa Parole Donne la Vie ✨",
		"Reposez-vous dans Ses Promesses 📖",
		"Approchez-vous de Dieu 🙏",
		"Laissez la Foi Vous Guider ❤️",
		"Dieu est Votre Refuge ✨",
		"Suivez Ses Voies 📖",
		"Faites Confiance à Son Plan Parfait 🙏",
		"Vivez dans Sa Grâce ❤️",
		"Tenez-vous en Silence devant Dieu ✨",
		"Que Sa Lumière Brille en Vous 📖",
		"Réjouissez-vous de Sa Fidélité 🙏",
		"Recevez Sa Paix ❤️",
		"Marchez Humblement avec Dieu ✨",
		"Demeurez dans Sa Parole 📖"
	],

	de: [
		"Beginne mit Seinem Wort 📖",
		"Wandle in Seinem Licht ✨",
		"Vertraue heute auf den Herrn 🙏",
		"Seine Gnade genügt ❤️",
		"Suche Ihn von ganzem Herzen",
		"Lass Sein Wort dich führen 📖",
		"Hoffe auf den Herrn ✨",
		"Wähle heute den Glauben 🙏",
		"Gott ist deine Stärke ❤️",
		"Freue dich im Herrn ✨",
		"Stehe fest im Glauben 📖",
		"Seine Barmherzigkeit ist neu 🙏",
		"Wandle im Glauben ❤️",
		"Sei stark im Herrn ✨",
		"Freue dich an Seinem Wort 📖",
		"Gib deinen Tag Gott 🙏",
		"Richte deine Augen auf Jesus ❤️",
		"Sein Wort schenkt Leben ✨",
		"Ruhe in Seinen Verheißungen 📖",
		"Nahe dich zu Gott 🙏",
		"Lass den Glauben dich führen ❤️",
		"Gott ist deine Zuflucht ✨",
		"Folge Seinen Wegen 📖",
		"Vertraue Seinem vollkommenen Plan 🙏",
		"Lebe in Seiner Gnade ❤️",
		"Sei still vor Gott ✨",
		"Lass Sein Licht durch dich leuchten 📖",
		"Freue dich über Seine Treue 🙏",
		"Empfange Seinen Frieden ❤️",
		"Wandle demütig mit Gott ✨",
		"Bleibe in Seinem Wort 📖"
	],

	ru: [
		"Начните с Его Слова 📖",
		"Ходите в Его Свете ✨",
		"Доверьтесь Господу сегодня 🙏",
		"Его благодати достаточно ❤️",
		"Ищите Его всем сердцем",
		"Пусть Его Слово ведёт вас 📖",
		"Надейтесь на Господа ✨",
		"Выберите веру сегодня 🙏",
		"Бог — ваша сила ❤️",
		"Радуйтесь о Господе ✨",
		"Стойте твёрдо в вере 📖",
		"Его милости обновляются 🙏",
		"Ходите верой ❤️",
		"Укрепляйтесь в Господе ✨",
		"Утешайтесь Его Словом 📖",
		"Отдайте свой день Богу 🙏",
		"Взирайте на Иисуса ❤️",
		"Его Слово даёт жизнь ✨",
		"Покойтесь в Его обетованиях 📖",
		"Приблизьтесь к Богу 🙏",
		"Пусть вера ведёт вас ❤️",
		"Бог — ваше убежище ✨",
		"Следуйте Его путями 📖",
		"Доверьтесь Его совершенному плану 🙏",
		"Живите в Его благодати ❤️",
		"Будьте спокойны перед Богом ✨",
		"Пусть Его свет сияет через вас 📖",
		"Радуйтесь Его верности 🙏",
		"Примите Его мир ❤️",
		"Смиренно ходите с Богом ✨",
		"Пребывайте в Его Слове 📖"
	],

	hi: [
		"उसके वचन से दिन शुरू करें 📖",
		"उसके प्रकाश में चलें ✨",
		"आज प्रभु पर भरोसा रखें 🙏",
		"उसका अनुग्रह पर्याप्त है ❤️",
		"पूरे मन से उसे खोजें",
		"उसका वचन आपका मार्गदर्शन करे 📖",
		"यहोवा पर आशा रखें ✨",
		"आज विश्वास को चुनें 🙏",
		"परमेश्वर आपकी शक्ति है ❤️",
		"प्रभु में आनन्दित हों ✨",
		"विश्वास में दृढ़ रहें 📖",
		"उसकी करुणा नई होती है 🙏",
		"विश्वास से चलें ❤️",
		"प्रभु में बलवन्त हों ✨",
		"उसके वचन में आनन्दित हों 📖",
		"अपना दिन परमेश्वर को दें 🙏",
		"अपनी आँखें यीशु पर लगाए रखें ❤️",
		"उसका वचन जीवन देता है ✨",
		"उसकी प्रतिज्ञाओं में विश्राम करें 📖",
		"परमेश्वर के निकट आएँ 🙏",
		"विश्वास को अपना मार्गदर्शक बनाएँ ❤️",
		"परमेश्वर आपका शरणस्थान है ✨",
		"उसके मार्गों पर चलें 📖",
		"उसकी उत्तम योजना पर भरोसा रखें 🙏",
		"उसके अनुग्रह में जीवन बिताएँ ❤️",
		"परमेश्वर के सामने शांत रहें ✨",
		"उसका प्रकाश आपके द्वारा चमके 📖",
		"उसकी विश्वासयोग्यता में आनन्दित हों 🙏",
		"उसकी शांति ग्रहण करें ❤️",
		"परमेश्वर के साथ नम्रता से चलें ✨",
		"उसके वचन में बने रहें 📖"
	],

	te: [
		"ఆయన వాక్యంతో రోజును ప్రారంభించండి 📖",
		"ఆయన వెలుగులో నడవండి ✨",
		"ఈ రోజు ప్రభువును నమ్మండి 🙏",
		"ఆయన కృప మీకు చాలును ❤️",
		"పూర్ణ హృదయంతో ఆయనను వెదకండి",
		"ఆయన వాక్యం మిమ్మల్ని నడిపించుగాక 📖",
		"యెహోవాపై నిరీక్షణ ఉంచండి ✨",
		"ఈ రోజు విశ్వాసాన్ని ఎంచుకోండి 🙏",
		"దేవుడే మీ బలం ❤️",
		"ప్రభువులో ఆనందించండి ✨",
		"విశ్వాసంలో స్థిరంగా నిలబడండి 📖",
		"ఆయన కనికరములు నూతనమవుతాయి 🙏",
		"విశ్వాసంతో నడవండి ❤️",
		"ప్రభువులో బలపడండి ✨",
		"ఆయన వాక్యంలో ఆనందించండి 📖",
		"మీ రోజును దేవునికి సమర్పించండి 🙏",
		"మీ కన్నులు యేసుపై నిలపండి ❤️",
		"ఆయన వాక్యం జీవాన్ని ఇస్తుంది ✨",
		"ఆయన వాగ్దానాలలో విశ్రాంతి పొందండి 📖",
		"దేవునికి సమీపంగా రండి 🙏",
		"విశ్వాసం మిమ్మల్ని నడిపించనివ్వండి ❤️",
		"దేవుడే మీ ఆశ్రయం ✨",
		"ఆయన మార్గాలలో నడవండి 📖",
		"ఆయన పరిపూర్ణ ప్రణాళికను నమ్మండి 🙏",
		"ఆయన కృపలో జీవించండి ❤️",
		"దేవుని సన్నిధిలో నిశ్చలంగా ఉండండి ✨",
		"ఆయన వెలుగు మీ ద్వారా ప్రకాశించుగాక 📖",
		"ఆయన విశ్వసనీయతలో ఆనందించండి 🙏",
		"ఆయన సమాధానాన్ని పొందండి ❤️",
		"మీ దేవునితో వినయంగా నడవండి ✨",
		"ఆయన వాక్యంలో నిలిచియుండండి 📖"
	],

	ta: [
		"அவருடைய வார்த்தையுடன் நாளைத் தொடங்குங்கள் 📖",
		"அவருடைய வெளிச்சத்தில் நடங்கள் ✨",
		"இன்று கர்த்தரை நம்புங்கள் 🙏",
		"அவருடைய கிருபை உங்களுக்குப் போதும் ❤️",
		"முழு இருதயத்தோடு அவரைத் தேடுங்கள்",
		"அவருடைய வார்த்தை உங்களை வழிநடத்தட்டும் 📖",
		"கர்த்தர்மேல் நம்பிக்கை வையுங்கள் ✨",
		"இன்று விசுவாசத்தைத் தேர்ந்தெடுங்கள் 🙏",
		"தேவனே உங்கள் பெலன் ❤️",
		"கர்த்தரில் மகிழ்ச்சியாயிருங்கள் ✨",
		"விசுவாசத்தில் உறுதியாக நில்லுங்கள் 📖",
		"அவருடைய இரக்கங்கள் புதிதாகின்றன 🙏",
		"விசுவாசத்தினால் நடங்கள் ❤️",
		"கர்த்தரில் பெலப்படுங்கள் ✨",
		"அவருடைய வார்த்தையில் மகிழுங்கள் 📖",
		"உங்கள் நாளை தேவனிடம் ஒப்புக்கொடுங்கள் 🙏",
		"உங்கள் கண்களை இயேசுவின்மேல் வையுங்கள் ❤️",
		"அவருடைய வார்த்தை ஜீவனைத் தருகிறது ✨",
		"அவருடைய வாக்குத்தத்தங்களில் இளைப்பாறுங்கள் 📖",
		"தேவனிடம் நெருங்கி வாருங்கள் 🙏",
		"விசுவாசம் உங்களை வழிநடத்தட்டும் ❤️",
		"தேவனே உங்கள் அடைக்கலம் ✨",
		"அவருடைய வழிகளில் நடங்கள் 📖",
		"அவருடைய பரிபூரண திட்டத்தை நம்புங்கள் 🙏",
		"அவருடைய கிருபையில் வாழுங்கள் ❤️",
		"தேவனுக்கு முன்பாக அமைதியாக இருங்கள் ✨",
		"அவருடைய வெளிச்சம் உங்கள் மூலம் பிரகாசிக்கட்டும் 📖",
		"அவருடைய உண்மைத்தன்மையில் மகிழுங்கள் 🙏",
		"அவருடைய சமாதானத்தைப் பெற்றுக்கொள்ளுங்கள் ❤️",
		"உங்கள் தேவனோடு தாழ்மையாய் நடங்கள் ✨",
		"அவருடைய வார்த்தையில் நிலைத்திருங்கள் 📖"
	],

	ko: [
		"그분의 말씀으로 시작하세요 📖",
		"그분의 빛 가운데 걸으세요 ✨",
		"오늘 주님을 신뢰하세요 🙏",
		"그분의 은혜는 충분합니다 ❤️",
		"온 마음으로 그분을 찾으세요",
		"그분의 말씀이 당신을 인도하게 하세요 📖",
		"주님께 소망을 두세요 ✨",
		"오늘 믿음을 선택하세요 🙏",
		"하나님은 당신의 힘입니다 ❤️",
		"주님 안에서 기뻐하세요 ✨",
		"믿음 안에 굳게 서세요 📖",
		"그분의 긍휼은 새롭습니다 🙏",
		"믿음으로 걸으세요 ❤️",
		"주님 안에서 강해지세요 ✨",
		"그분의 말씀을 기뻐하세요 📖",
		"하루를 하나님께 맡기세요 🙏",
		"예수님께 시선을 고정하세요 ❤️",
		"그분의 말씀은 생명을 줍니다 ✨",
		"그분의 약속 안에서 쉬세요 📖",
		"하나님께 가까이 나아가세요 🙏",
		"믿음이 당신을 인도하게 하세요 ❤️",
		"하나님은 당신의 피난처입니다 ✨",
		"그분의 길을 따르세요 📖",
		"그분의 완전한 계획을 신뢰하세요 🙏",
		"그분의 은혜 안에 거하세요 ❤️",
		"하나님 앞에서 잠잠하세요 ✨",
		"그분의 빛이 당신을 통해 비치게 하세요 📖",
		"그분의 신실하심을 기뻐하세요 🙏",
		"그분의 평안을 받으세요 ❤️",
		"하나님과 겸손히 동행하세요 ✨",
		"그분의 말씀 안에 거하세요 📖"
	],

	ar: [
		"ابدأ بكلمته 📖",
		"اسلك في نوره ✨",
		"ثق بالرب اليوم 🙏",
		"نعمته تكفيك ❤️",
		"اطلبه من كل قلبك",
		"دع كلمته تقودك 📖",
		"ارجُ الرب ✨",
		"اختر الإيمان اليوم 🙏",
		"الله قوتك ❤️",
		"افرح في الرب ✨",
		"اثبت في الإيمان 📖",
		"مراحمه جديدة 🙏",
		"اسلك بالإيمان ❤️",
		"تقوَّ في الرب ✨",
		"افرح بكلمته 📖",
		"سلّم يومك لله 🙏",
		"ثبّت عينيك على يسوع ❤️",
		"كلمته تمنح الحياة ✨",
		"استرح في وعوده 📖",
		"اقترب إلى الله 🙏",
		"دع الإيمان يقودك ❤️",
		"الله ملجؤك ✨",
		"اسلك في طرقه 📖",
		"ثق في خطته الكاملة 🙏",
		"عش في نعمته ❤️",
		"اهدأ أمام الله ✨",
		"دع نوره يشرق من خلالك 📖",
		"افرح بأمانته 🙏",
		"اقبل سلامه ❤️",
		"اسلك بتواضع مع إلهك ✨",
		"اثبت في كلمته 📖"
	]

};

export const eveningTitles: Record<string, string[]> = {
	eng: [
		"Rest in His Promises 🌙",
		"A Moment to Reflect ❤️",
		"Let His Peace Fill You ✨",
		"Hold Fast to His Word 📖",
		"God Is Your Refuge 🙏",
		"Leave Your Cares with Him ❤️",
		"His Love Never Fails ✨",
		"Be Still Before Him 🕊️",
		"Trust Him with Your Heart 📖",
		"His Peace Is with You 🙏",
		"Remember His Faithfulness ❤️",
		"Rest in His Grace ✨",
		"Draw Near to God 📖",
		"He Will Sustain You 🙏",
		"Let His Word Bring Peace ❤️",
		"Hope in His Promises ✨",
		"Give Thanks to the Lord 📖",
		"His Mercy Endures Forever 🙏",
		"Be Still and Trust Him ❤️",
		"His Word Is Your Light ✨",
		"Cast Your Cares on Him 📖",
		"God Holds You Close 🙏",
		"Rejoice in His Goodness ❤️",
		"His Faithfulness Is Great ✨",
		"Rest in God's Love 📖",
		"Commit Your Way to Him 🙏",
		"Peace for Your Heart ❤️",
		"His Promises Stand Forever ✨",
		"Keep Faith in Your Heart 📖",
		"Rest in God's Faithfulness 🙏",
		"Abide in His Word ❤️"
	],

	en: [
		"Rest in His Promises 🌙",
		"A Moment to Reflect ❤️",
		"Let His Peace Fill You ✨",
		"Hold Fast to His Word 📖",
		"God Is Your Refuge 🙏",
		"Leave Your Cares with Him ❤️",
		"His Love Never Fails ✨",
		"Be Still Before Him 🕊️",
		"Trust Him with Your Heart 📖",
		"His Peace Is with You 🙏",
		"Remember His Faithfulness ❤️",
		"Rest in His Grace ✨",
		"Draw Near to God 📖",
		"He Will Sustain You 🙏",
		"Let His Word Bring Peace ❤️",
		"Hope in His Promises ✨",
		"Give Thanks to the Lord 📖",
		"His Mercy Endures Forever 🙏",
		"Be Still and Trust Him ❤️",
		"His Word Is Your Light ✨",
		"Cast Your Cares on Him 📖",
		"God Holds You Close 🙏",
		"Rejoice in His Goodness ❤️",
		"His Faithfulness Is Great ✨",
		"Rest in God's Love 📖",
		"Commit Your Way to Him 🙏",
		"Peace for Your Heart ❤️",
		"His Promises Stand Forever ✨",
		"Keep Faith in Your Heart 📖",
		"Rest in God's Faithfulness 🙏",
		"Abide in His Word ❤️"
	],

	es: [
		"Descansa en Sus Promesas 🌙",
		"Un Momento para Reflexionar ❤️",
		"Deja que Su Paz te Llene ✨",
		"Aférrate a Su Palabra 📖",
		"Dios es tu Refugio 🙏",
		"Deja tus Preocupaciones en Sus Manos ❤️",
		"Su Amor Nunca Falla ✨",
		"Quédate en Silencio ante Él 🕊️",
		"Confía en Él de Todo Corazón 📖",
		"Su Paz está Contigo 🙏",
		"Recuerda Su Fidelidad ❤️",
		"Descansa en Su Gracia ✨",
		"Acércate a Dios 📖",
		"Él te Sostendrá 🙏",
		"Deja que Su Palabra Traiga Paz ❤️",
		"Espera en Sus Promesas ✨",
		"Da Gracias al Señor 📖",
		"Su Misericordia Permanece para Siempre 🙏",
		"Quédate Quieto y Confía en Él ❤️",
		"Su Palabra es tu Luz ✨",
		"Entrégale tus Preocupaciones 📖",
		"Dios te Sostiene Cerca 🙏",
		"Alégrate en Su Bondad ❤️",
		"Grande es Su Fidelidad ✨",
		"Descansa en el Amor de Dios 📖",
		"Encomienda tu Camino a Él 🙏",
		"Paz para tu Corazón ❤️",
		"Sus Promesas Permanecen para Siempre ✨",
		"Mantén la Fe en tu Corazón 📖",
		"Descansa en la Fidelidad de Dios 🙏",
		"Permanece en Su Palabra ❤️"
	],

	pt: [
		"Descanse nas Suas Promessas 🌙",
		"Um Momento para Refletir ❤️",
		"Deixe a Sua Paz Encher Você ✨",
		"Apegue-se à Sua Palavra 📖",
		"Deus é o Seu Refúgio 🙏",
		"Entregue Suas Preocupações a Ele ❤️",
		"O Seu Amor Nunca Falha ✨",
		"Aquieta-te diante dEle 🕊️",
		"Confie nEle de Todo o Coração 📖",
		"A Sua Paz Está com Você 🙏",
		"Lembre-se da Sua Fidelidade ❤️",
		"Descanse na Sua Graça ✨",
		"Aproxime-se de Deus 📖",
		"Ele Sustentará Você 🙏",
		"Deixe a Sua Palavra Trazer Paz ❤️",
		"Espere nas Suas Promessas ✨",
		"Dê Graças ao Senhor 📖",
		"A Sua Misericórdia Dura para Sempre 🙏",
		"Aquieta-te e Confie nEle ❤️",
		"A Sua Palavra é a Sua Luz ✨",
		"Entregue a Ele as Suas Preocupações 📖",
		"Deus Está Perto de Você 🙏",
		"Alegre-se na Sua Bondade ❤️",
		"Grande é a Sua Fidelidade ✨",
		"Descanse no Amor de Deus 📖",
		"Entregue o Seu Caminho a Ele 🙏",
		"Paz para o Seu Coração ❤️",
		"As Suas Promessas Permanecem para Sempre ✨",
		"Mantenha a Fé no Seu Coração 📖",
		"Descanse na Fidelidade de Deus 🙏",
		"Permaneça na Sua Palavra ❤️"
	],

	fr: [
		"Reposez-vous dans Ses Promesses 🌙",
		"Un Moment pour Réfléchir ❤️",
		"Que Sa Paix Remplisse Votre Cœur ✨",
		"Attachez-vous à Sa Parole 📖",
		"Dieu est Votre Refuge 🙏",
		"Remettez-Lui Vos Soucis ❤️",
		"Son Amour ne Déçoit Jamais ✨",
		"Tenez-vous en Silence devant Lui 🕊️",
		"Faites-Lui Confiance de Tout Votre Cœur 📖",
		"Sa Paix est avec Vous 🙏",
		"Souvenez-vous de Sa Fidélité ❤️",
		"Reposez-vous dans Sa Grâce ✨",
		"Approchez-vous de Dieu 📖",
		"Il Vous Soutiendra 🙏",
		"Que Sa Parole Vous Apporte la Paix ❤️",
		"Espérez en Ses Promesses ✨",
		"Rendez Grâce au Seigneur 📖",
		"Sa Miséricorde Dure à Toujours 🙏",
		"Soyez Calmes et Faites-Lui Confiance ❤️",
		"Sa Parole est Votre Lumière ✨",
		"Remettez-Lui Vos Soucis 📖",
		"Dieu Vous Tient Près de Lui 🙏",
		"Réjouissez-vous de Sa Bonté ❤️",
		"Grande est Sa Fidélité ✨",
		"Reposez-vous dans l'Amour de Dieu 📖",
		"Confiez-Lui Votre Chemin 🙏",
		"La Paix pour Votre Cœur ❤️",
		"Ses Promesses Demeurent à Jamais ✨",
		"Gardez la Foi dans Votre Cœur 📖",
		"Reposez-vous dans la Fidélité de Dieu 🙏",
		"Demeurez dans Sa Parole ❤️"
	],

	de: [
		"Ruhe in Seinen Verheißungen 🌙",
		"Ein Moment zum Nachdenken ❤️",
		"Lass Seinen Frieden dich erfüllen ✨",
		"Halte dich an Sein Wort 📖",
		"Gott ist deine Zuflucht 🙏",
		"Gib deine Sorgen bei Ihm ab ❤️",
		"Seine Liebe versagt nie ✨",
		"Sei still vor Ihm 🕊️",
		"Vertraue Ihm von ganzem Herzen 📖",
		"Sein Friede ist mit dir 🙏",
		"Erinnere dich an Seine Treue ❤️",
		"Ruhe in Seiner Gnade ✨",
		"Nahe dich zu Gott 📖",
		"Er wird dich tragen 🙏",
		"Lass Sein Wort Frieden bringen ❤️",
		"Hoffe auf Seine Verheißungen ✨",
		"Danke dem Herrn 📖",
		"Seine Barmherzigkeit bleibt ewig 🙏",
		"Sei still und vertraue Ihm ❤️",
		"Sein Wort ist dein Licht ✨",
		"Wirf deine Sorgen auf Ihn 📖",
		"Gott hält dich nahe bei sich 🙏",
		"Freue dich über Seine Güte ❤️",
		"Groß ist Seine Treue ✨",
		"Ruhe in Gottes Liebe 📖",
		"Befiehl Ihm deinen Weg 🙏",
		"Frieden für dein Herz ❤️",
		"Seine Verheißungen bleiben ewig ✨",
		"Bewahre den Glauben in deinem Herzen 📖",
		"Ruhe in Gottes Treue 🙏",
		"Bleibe in Seinem Wort ❤️"
	],

	ru: [
		"Покойтесь в Его обетованиях 🌙",
		"Мгновение для размышлений ❤️",
		"Пусть Его мир наполнит вас ✨",
		"Держитесь Его Слова 📖",
		"Бог — ваше убежище 🙏",
		"Оставьте свои заботы Ему ❤️",
		"Его любовь никогда не подведёт ✨",
		"Будьте спокойны перед Ним 🕊️",
		"Доверьтесь Ему всем сердцем 📖",
		"Его мир с вами 🙏",
		"Помните о Его верности ❤️",
		"Покойтесь в Его благодати ✨",
		"Приблизьтесь к Богу 📖",
		"Он поддержит вас 🙏",
		"Пусть Его Слово принесёт мир ❤️",
		"Надейтесь на Его обетования ✨",
		"Благодарите Господа 📖",
		"Его милость вовек 🙏",
		"Будьте спокойны и доверьтесь Ему ❤️",
		"Его Слово — ваш свет ✨",
		"Возложите на Него ваши заботы 📖",
		"Бог держит вас близко 🙏",
		"Радуйтесь Его благости ❤️",
		"Велика Его верность ✨",
		"Покойтесь в Божьей любви 📖",
		"Предайте Ему свой путь 🙏",
		"Мир вашему сердцу ❤️",
		"Его обетования пребывают вовек ✨",
		"Храните веру в сердце 📖",
		"Покойтесь в верности Бога 🙏",
		"Пребывайте в Его Слове ❤️"
	],

	hi: [
		"उसकी प्रतिज्ञाओं में विश्राम करें 🌙",
		"मनन करने का एक पल ❤️",
		"उसकी शांति आपको भर दे ✨",
		"उसके वचन को थामे रहें 📖",
		"परमेश्वर आपका शरणस्थान है 🙏",
		"अपनी चिंताएँ उसे सौंप दें ❤️",
		"उसका प्रेम कभी विफल नहीं होता ✨",
		"उसके सामने शांत रहें 🕊️",
		"पूरे मन से उस पर भरोसा रखें 📖",
		"उसकी शांति आपके साथ है 🙏",
		"उसकी विश्वासयोग्यता को याद रखें ❤️",
		"उसके अनुग्रह में विश्राम करें ✨",
		"परमेश्वर के निकट आएँ 📖",
		"वह आपको संभालेगा 🙏",
		"उसका वचन शांति दे ❤️",
		"उसकी प्रतिज्ञाओं पर आशा रखें ✨",
		"यहोवा का धन्यवाद करें 📖",
		"उसकी करुणा सदा बनी रहती है 🙏",
		"शांत रहें और उस पर भरोसा रखें ❤️",
		"उसका वचन आपका प्रकाश है ✨",
		"अपनी चिंताएँ उस पर डाल दें 📖",
		"परमेश्वर आपको थामे हुए है 🙏",
		"उसकी भलाई में आनन्दित हों ❤️",
		"उसकी विश्वासयोग्यता महान है ✨",
		"परमेश्वर के प्रेम में विश्राम करें 📖",
		"अपना मार्ग उसे सौंप दें 🙏",
		"आपके हृदय के लिए शांति ❤️",
		"उसकी प्रतिज्ञाएँ सदा बनी रहती हैं ✨",
		"अपने हृदय में विश्वास बनाए रखें 📖",
		"परमेश्वर की विश्वासयोग्यता में विश्राम करें 🙏",
		"उसके वचन में बने रहें ❤️"
	],

	te: [
		"ఆయన వాగ్దానాలలో విశ్రాంతి పొందండి 🌙",
		"ఆలోచించడానికి ఒక క్షణం ❤️",
		"ఆయన సమాధానం మిమ్మల్ని నింపుగాక ✨",
		"ఆయన వాక్యాన్ని గట్టిగా పట్టుకోండి 📖",
		"దేవుడే మీ ఆశ్రయం 🙏",
		"మీ చింతలను ఆయనకు అప్పగించండి ❤️",
		"ఆయన ప్రేమ ఎన్నటికీ విఫలముకాదు ✨",
		"ఆయన సన్నిధిలో నిశ్చలంగా ఉండండి 🕊️",
		"పూర్ణ హృదయంతో ఆయనను నమ్మండి 📖",
		"ఆయన సమాధానం మీతో ఉంది 🙏",
		"ఆయన విశ్వసనీయతను జ్ఞాపకం చేసుకోండి ❤️",
		"ఆయన కృపలో విశ్రాంతి పొందండి ✨",
		"దేవునికి సమీపంగా రండి 📖",
		"ఆయన మిమ్మల్ని ఆదరిస్తాడు 🙏",
		"ఆయన వాక్యం సమాధానాన్ని ఇవ్వుగాక ❤️",
		"ఆయన వాగ్దానాలపై నిరీక్షణ ఉంచండి ✨",
		"ప్రభువుకు కృతజ్ఞతలు చెల్లించండి 📖",
		"ఆయన కృప నిరంతరం ఉంటుంది 🙏",
		"నిశ్చలంగా ఉండి ఆయనను నమ్మండి ❤️",
		"ఆయన వాక్యం మీ వెలుగు ✨",
		"మీ చింతలను ఆయనపై వేయండి 📖",
		"దేవుడు మిమ్మల్ని దగ్గరగా కాపాడుతున్నాడు 🙏",
		"ఆయన మంచితనంలో ఆనందించండి ❤️",
		"ఆయన విశ్వసనీయత గొప్పది ✨",
		"దేవుని ప్రేమలో విశ్రాంతి పొందండి 📖",
		"మీ మార్గాన్ని ఆయనకు అప్పగించండి 🙏",
		"మీ హృదయానికి సమాధానం ❤️",
		"ఆయన వాగ్దానాలు నిత్యము నిలిచియుంటాయి ✨",
		"మీ హృదయంలో విశ్వాసాన్ని కాపాడుకోండి 📖",
		"దేవుని విశ్వసనీయతలో విశ్రాంతి పొందండి 🙏",
		"ఆయన వాక్యంలో నిలిచియుండండి ❤️"
	],

	ta: [
		"அவருடைய வாக்குத்தத்தங்களில் இளைப்பாறுங்கள் 🌙",
		"சிந்திக்க ஒரு தருணம் ❤️",
		"அவருடைய சமாதானம் உங்களை நிரப்பட்டும் ✨",
		"அவருடைய வார்த்தையைப் பற்றிக்கொள்ளுங்கள் 📖",
		"தேவனே உங்கள் அடைக்கலம் 🙏",
		"உங்கள் கவலைகளை அவரிடம் ஒப்புக்கொடுங்கள் ❤️",
		"அவருடைய அன்பு ஒருபோதும் தோல்வியடையாது ✨",
		"அவருக்கு முன்பாக அமைதியாக இருங்கள் 🕊️",
		"முழு இருதயத்தோடு அவரை நம்புங்கள் 📖",
		"அவருடைய சமாதானம் உங்களோடு இருக்கிறது 🙏",
		"அவருடைய உண்மைத்தன்மையை நினைவுகூருங்கள் ❤️",
		"அவருடைய கிருபையில் இளைப்பாறுங்கள் ✨",
		"தேவனிடம் நெருங்கி வாருங்கள் 📖",
		"அவர் உங்களைத் தாங்குவார் 🙏",
		"அவருடைய வார்த்தை சமாதானம் தரட்டும் ❤️",
		"அவருடைய வாக்குத்தத்தங்களில் நம்பிக்கை வையுங்கள் ✨",
		"கர்த்தருக்கு நன்றி செலுத்துங்கள் 📖",
		"அவருடைய இரக்கம் என்றென்றும் உள்ளது 🙏",
		"அமைதியாக இருந்து அவரை நம்புங்கள் ❤️",
		"அவருடைய வார்த்தை உங்கள் வெளிச்சம் ✨",
		"உங்கள் கவலைகளை அவர்மேல் வையுங்கள் 📖",
		"தேவன் உங்களை அருகில் தாங்குகிறார் 🙏",
		"அவருடைய நன்மையில் மகிழுங்கள் ❤️",
		"அவருடைய உண்மைத்தன்மை பெரியது ✨",
		"தேவனுடைய அன்பில் இளைப்பாறுங்கள் 📖",
		"உங்கள் வழியை அவரிடம் ஒப்புக்கொடுங்கள் 🙏",
		"உங்கள் இருதயத்திற்கு சமாதானம் ❤️",
		"அவருடைய வாக்குத்தத்தங்கள் என்றென்றும் நிலைத்திருக்கும் ✨",
		"உங்கள் இருதயத்தில் விசுவாசத்தை காத்துக்கொள்ளுங்கள் 📖",
		"தேவனுடைய உண்மைத்தன்மையில் இளைப்பாறுங்கள் 🙏",
		"அவருடைய வார்த்தையில் நிலைத்திருங்கள் ❤️"
	],

	ko: [
		"그분의 약속 안에서 쉬세요 🌙",
		"잠시 묵상하는 시간 ❤️",
		"그분의 평안으로 마음을 채우세요 ✨",
		"그분의 말씀을 굳게 붙드세요 📖",
		"하나님은 당신의 피난처입니다 🙏",
		"모든 염려를 그분께 맡기세요 ❤️",
		"그분의 사랑은 결코 실패하지 않습니다 ✨",
		"그분 앞에서 잠잠하세요 🕊️",
		"온 마음으로 그분을 신뢰하세요 📖",
		"그분의 평안이 당신과 함께합니다 🙏",
		"그분의 신실하심을 기억하세요 ❤️",
		"그분의 은혜 안에서 쉬세요 ✨",
		"하나님께 가까이 나아가세요 📖",
		"그분이 당신을 붙드실 것입니다 🙏",
		"그분의 말씀이 평안을 가져오게 하세요 ❤️",
		"그분의 약속을 소망하세요 ✨",
		"주님께 감사하세요 📖",
		"그분의 자비는 영원합니다 🙏",
		"잠잠히 그분을 신뢰하세요 ❤️",
		"그분의 말씀은 당신의 빛입니다 ✨",
		"모든 염려를 그분께 맡기세요 📖",
		"하나님이 당신을 가까이 붙드십니다 🙏",
		"그분의 선하심을 기뻐하세요 ❤️",
		"그분의 신실하심은 큽니다 ✨",
		"하나님의 사랑 안에서 쉬세요 📖",
		"당신의 길을 그분께 맡기세요 🙏",
		"당신의 마음에 평안을 ❤️",
		"그분의 약속은 영원히 서 있습니다 ✨",
		"마음에 믿음을 지키세요 📖",
		"하나님의 신실하심 안에서 쉬세요 🙏",
		"그분의 말씀 안에 거하세요 ❤️"
	],

	ar: [
		"استرح في وعوده 🌙",
		"لحظة للتأمل ❤️",
		"دع سلامه يملأك ✨",
		"تمسك بكلمته 📖",
		"الله ملجؤك 🙏",
		"اترك همومك عنده ❤️",
		"محبته لا تفشل أبدًا ✨",
		"اهدأ أمامه 🕊️",
		"ثق به من كل قلبك 📖",
		"سلامه معك 🙏",
		"تذكر أمانته ❤️",
		"استرح في نعمته ✨",
		"اقترب إلى الله 📖",
		"هو يسندك 🙏",
		"دع كلمته تمنحك السلام ❤️",
		"ارجُ وعوده ✨",
		"اشكر الرب 📖",
		"رحمته إلى الأبد 🙏",
		"اهدأ وثق به ❤️",
		"كلمته نورك ✨",
		"ألقِ همومك عليه 📖",
		"الله يمسك بك 🙏",
		"افرح بصلاحه ❤️",
		"عظيم هو أمانته ✨",
		"استرح في محبة الله 📖",
		"سلّم طريقك له 🙏",
		"سلام لقلبك ❤️",
		"وعوده ثابتة إلى الأبد ✨",
		"احفظ الإيمان في قلبك 📖",
		"استرح في أمانة الله 🙏",
		"اثبت في كلمته ❤️"
	]

};


export const genericMorningTitles: Record<string, string> = {

	eng:
		"God's Word for Your Day ✨",

	en:
		"God's Word for Your Day ✨",

	es:
		"La Palabra de Dios para tu Día ✨",

	pt:
		"A Palavra de Deus para o Seu Dia ✨",

	fr:
		"La Parole de Dieu pour Votre Journée ✨",

	de:
		"Gottes Wort für deinen Tag ✨",

	ru:
		"Слово Божье для вашего дня ✨",

	hi:
		"आपके दिन के लिए परमेश्वर का वचन ✨",

	te:
		"మీ రోజు కోసం దేవుని వాక్యం ✨",

	ta:
		"உங்கள் நாளுக்கான தேவனுடைய வார்த்தை ✨",

	ko:
		"오늘을 위한 하나님의 말씀 ✨",

	ar:
		"كلمة الله ليومك ✨"
};


export const genericEveningTitles: Record<string, string> = {

	eng:
		"Rest in God's Word ✨",

	en:
		"Rest in God's Word ✨",

	es:
		"Descansa en la Palabra de Dios ✨",

	pt:
		"Descanse na Palavra de Deus ✨",

	fr:
		"Reposez-vous dans la Parole de Dieu ✨",

	de:
		"Ruhe in Gottes Wort ✨",

	ru:
		"Покойтесь в Слове Божьем ✨",

	hi:
		"परमेश्वर के वचन में विश्राम करें ✨",

	te:
		"దేవుని వాక్యంలో విశ్రాంతి పొందండి ✨",

	ta:
		"தேவனுடைய வார்த்தையில் இளைப்பாறுங்கள் ✨",

	ko:
		"하나님의 말씀 안에서 쉬세요 ✨",

	ar:
		"استرح في كلمة الله ✨"
};